name: ci

on:
  pull_request:
  push:

env:
  GO_VERSION: 1.17.x

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v2.4.0

      - uses: actions/setup-go@f6164bd8c8acb4a71fb2791a8b6c4024ff038dab # v2.1.5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: build
        run: |
          make apko
          ./apko version

      - uses: goreleaser/goreleaser-action@b953231f81b8dfd023c58e0854a721e35037f28b # v2.8.1
        with:
          version: v1.5.0
          install-only: true

      - name: snapshot
        run: |
          make snapshot
          ./dist/apko-build_linux_amd64/apko version
