name: ci

on:
  pull_request:
  push:

env:
  GO_VERSION: 1.17.x

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v2.4.0

      - uses: actions/setup-go@fcdc43634adb5f7ae75a9d7a9b9361790f7293e2 # v2.1.5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: build
        run: |
          make apko
          ./apko version

      - uses: goreleaser/goreleaser-action@b953231f81b8dfd023c58e0854a721e35037f28b # v2.8.1
        with:
          version: v1.5.0
          install-only: true

      - name: snapshot
        run: |
          make snapshot
          ./dist/apko-build_linux_amd64/apko version
