name: ci

on:
  pull_request:
  push:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v2.4.0

      - uses: actions/setup-go@268d8c0ca0432bb2cf416faae41297df9d262d7f # v2.1.5
        with:
          go-version: 1.19
          check-latest: true

      - name: build
        run: |
          make apko
          ./apko version

      - uses: goreleaser/goreleaser-action@b508e2e3ef3b19d4e4146d4f8fb3ba9db644a757 # v2.8.1
        with:
          version: latest
          install-only: true

      - name: snapshot
        run: |
          make snapshot
          ./dist/apko-build_linux_amd64_v1/apko version
