name: mink e2e

on:
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  mink-e2e:
    name: apko task
    runs-on: ubuntu-latest

    env:
      KO_DOCKER_REPO: registry.local:5000/chainguard

    steps:
    - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v2.4.0

    - uses: actions/setup-go@fcdc43634adb5f7ae75a9d7a9b9361790f7293e2 # v2.1.5
      with:
        go-version: '1.17.x'

    - uses: imjasonh/setup-ko@2c3450ca27f6e6f2b02e72a40f2163c281a1f675 # v0.4
      with:
        version: v0.10.0

    - uses: chainguard-dev/actions/setup-kind@main
      with:
        k8s-version: v1.22.x
        registry-authority: registry.local:5000

    - uses: chainguard-dev/actions/setup-mink@main
      with:
        version: 1.1.0

    - name: "Configure and install mink"
      run: |
        cat > $HOME/.mink.yaml <<EOF
        # Bundle source context to here by default!
        bundle: ${KO_DOCKER_REPO}/bundle:latest
        # Send the resulting image here by default!
        image: ${KO_DOCKER_REPO}/image:latest
        EOF

        mink install

    - name: Build and install apko task
      run: |
        make ko-apply

    - name: Build examples
      run: |
        for cfg in $(find ./examples/ -name '*.yaml'); do
          DIGEST=$(mink run task apko -- --path=$cfg)

          echo $cfg produced: $DIGEST
        done

    - uses: chainguard-dev/actions/kind-diag@main
      if: ${{failure()}}
