name: verify

on:
  push:
  pull_request:

env:
  GO_VERSION: 1.17.x

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v2.4.0
      - uses: actions/setup-go@bfdd3570ce990073878bf10f6b2d79082de49492 # v2.2.0
        with:
          go-version:  ${{ env.GO_VERSION }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@b517f99ae23d86ecc4c0dec08dcf48d2336abc29 # v3.1.0
        timeout-minutes: 5
        with:
          version: v1.44.2
      - run: |
          go mod tidy
          git diff --exit-code
