name: verify

on:
  push:
  pull_request:

env:
  GO_VERSION: 1.17.x

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v2.4.0
      - uses: actions/setup-go@b22fbbc2921299758641fab08929b4ac52b32923 # v2.2.0
        with:
          go-version:  ${{ env.GO_VERSION }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@b517f99ae23d86ecc4c0dec08dcf48d2336abc29 # v3.1.0
        timeout-minutes: 5
        with:
          version: v1.44.2
      - run: |
          go mod tidy
          git diff --exit-code
